### ISSUE TITLE
Random sampler is get smallest for categorical generic enough

### ISSUE THREAD

**Issue by rheasukthanker** [whittle-org/whittle#108]
**Describe the bug**
Random sampler uses [0] and [-1] indexing which assumes the search space choices have been sorted, this might not always be correct. Could we use max and mix instead?

**Comment by aaronkl** [comment]
Good question! The problem with categorical is that they do not necessarily have a intrinsic structure, and might not have a numeric value in the first place. But I agree that using min / max is more principled approach.
