### ISSUE TITLE
deepspeed on gpus

### ISSUE THREAD

**Issue by rheasukthanker** [whittle-org/whittle#153]
**Describe the bug**
Importing deepspeed on gpus (tested on juwels) for FLOP profiling leads to "deepspeed.ops.op_builder.builder.MissingCUDAException: CUDA_HOME does not exist, unable to compile CUDA op(s)". Are we enforcing that deepspeed uses cpu accelerator?

@timurcarstensen could you look into this and try to reproduce this issue on juwels? Ideally we should not depend on CUDA_HOME environment variable.

**Comment by timurcarstensen** [comment]
Did you also test this on META?

**Comment by rheasukthanker** [comment]
Nope, only juwels, I think CUDA_HOME is a flag on meta, so should likely be fine there. I am wondering if we can prevent deepspeed from accessing this flag (which is triggered when using a gpu)?
