### ISSUE TITLE
Update doc strings 

### ISSUE THREAD

**Issue by rheasukthanker** [whittle-org/whittle#164]
**Is your feature request related to a problem? Please describe.**
Could we add doc strings to functions which are missing doc strings eg: https://github.com/whittle-org/whittle/blob/main/whittle/models/gpt/extract.py#L13. Ideally it would be nice to add docstrings to all main functions to improve documentation for the library.

**Comment by timurcarstensen** [comment]
One take on this: generally, yes. However, not if the function is very descriptive in what it does. I would leave this up to the contributor and then catch it in code review :)

**Comment by timurcarstensen** [comment]
Also: the docstring format is not consistent across the codebase. For example, in `whittle/search/local_search.py` has a different format than what we use elsewhere

**Comment by snikhil24** [comment]
I’d like to work on this issue. Please let me know if there’s a preferred format or any specific guidelines!
