### ISSUE TITLE
Change sub_network_head_size and query_groups to positional arguments

### ISSUE THREAD

**Issue by gabikadlecova** [whittle-org/whittle#165]
Small issue that came up while working on https://github.com/whittle-org/whittle/issues/146

Since we moved the computation of `sub_network_head_size` and `sub_network_query_groups` to `model.py`, they should be **positional arguments** in `causal_self_attention.py` (and `transformer_block.py`):

https://github.com/whittle-org/whittle/blob/a07ee5afef0f23b309a3a089cdf09ee3f75b359a/whittle/models/gpt/blocks/causal_self_attention.py#L48

Calling the function without any arguments causes `set_sub_network()` to crash:
```
 def set_sub_network(
        self,
        sub_network_n_embd: int,
        sub_network_n_head: int,
        sub_network_query_groups=None,
        sub_network_head_size=None,
    ):
        self.sub_network_n_embd = sub_network_n_embd
        self.sub_network_n_head = sub_network_n_head
        self.sub_network_query_groups = sub_network_query_groups
        self.sub_network_head_size = sub_network_head_size

        self.sub_network_qkv_shape = (
            self.sub_network_n_head + 2 * self.sub_network_query_groups   # this crashes
        ) * self.sub_network_head_size
```

It's not affecting anything right now, as we always call it with arguments that are not None. I suggest fixing it to avoid hidden errors in the future.

```
 def set_sub_network(
        self,
        sub_network_n_embd: int,
        sub_network_n_head: int,
        sub_network_query_groups: int,
        sub_network_head_size: int
    ):
```

**Comment by Jetoson** [comment]
@gabikadlecova can I work on this?
