### ISSUE TITLE
feat: add python 3.12 support

### ISSUE THREAD

**Issue by timurcarstensen** [whittle-org/whittle#166]
PyTorch, Lightning and LitGPT now support python 3.12. Let's add 3.12 to our list of supported versions. 

TODOs: 
- [ ] update `pyproject.toml` to allow usage of 3.12
- [ ] update GH actions workflows to also use 3.12 (make sure tests don't fail)
    - [ ] `unit-test.yml`
    - [ ] `run-examples.yml`

**Comment by snikhil24** [comment]
Hi @timurcarstensen !
Can I work on this issue?

**Comment by timurcarstensen** [comment]
Well then just submit a PR after reading and following our contribution guidelines :)

**Comment by snikhil24** [comment]
I’ve made the required changes and submitted a PR. Thanks :)
