### ISSUE TITLE
calling reset_parameters after init leads to crash

### ISSUE THREAD

**Issue by aaronkl** [whittle-org/whittle#194]
**Describe the bug**
Calling `reset_parameters` right after construction leads to a crash since we haven't initialized cos/sin.

**To Reproduce**
```
from litgpt.config import Config

from whittle.models.gpt import GPT

config = Config.from_name("pythia-70m")
config.fix_head_size = True
model = GPT(config)
model.reset_parameters()
```

**Additional context**
It seems that the error has been introduced in #181

**Comment by gabikadlecova** [comment]
The only thing that `reset_parameters()` does is that it resets the sin & cos of the rope_cache (same as in litgpt). Should I remove the function?

Side question - should we really compute the rope_cache in forward and not in the setter/set_sub_network? How expensive is it to recompute it in each forward pass? I know that there was an issue with FSDP (https://github.com/whittle-org/whittle/issues/156), but if it induces some costs in forward, maybe it's worth looking into it deeper.
@aaronkl

**Comment by aaronkl** [comment]
good question. wdyt @rheasukthanker ?

**Comment by rheasukthanker** [comment]
I think we need to keep cos, sin in init. I'll create a PR with the fix I already have for FSDP to fix this issue

**Comment by rheasukthanker** [comment]
Doesn't fail as of #203 now
