### ISSUE TITLE
[Build] torch CPU only version?

### ISSUE THREAD

**Issue by eddiebergman** [whittle-org/whittle#80]
Right now when I do `poetry install`, it install `torch` with all it's gpu dependencies. Makes a lot of sense given the scope of the project.

However given I don't have a GPU, I'm wondering if there's an option to make the torch cpu version an optional dependancy. I'm not sure how poetry works w.r.t. specific torch wheels (torch distribution of CPU builds is odd to say the least, also difficult to get right).

Feel free to close this issue if it's out of scope

**Comment by timurcarstensen** [comment]
Is this easier after moving away from `poetry`?

**Comment by eddiebergman** [comment]
Yes and No, for us directly yes, however through other dependancies that depend on torch, it would require a lot more work. I think it's better to just ignore it for now
