### ISSUE TITLE
Automatic release workflow

### ISSUE THREAD

**Issue by timurcarstensen** [whittle-org/whittle#92]
**Describe the solution you'd like**
A one-click release workflow that automatically compiles change logs from the PRs since the last release

**Additional context**
Implementation similar to that in [amltk](https://github.com/automl/amltk)

**Comment by timurcarstensen** [comment]
@eddiebergman what are the pre-requisites for this? Do we need to use commitizen or is naming our PRs in a certain way enough (e.g., chore, fix, docs)?

**Comment by eddiebergman** [comment]
You need everyone to conform to [conventional-commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) where [`commitizen`](https://commitizen-tools.github.io/commitizen/) is a pre-commit tool to enforce it. As you release from `main` and you do squash merges, you need to ensure that the squash merge name is folloing conventional commmits. Usually I do this by just checking that the PR name follows the convention. There's probably automated ways to check this but by having `commitizen` as a pre-commit, you get trained to do it pretty quickly by default so it's never been an issue. There's also backdoors out of it incase commits don't follow the convention.

Importantly, you need people to know about the difference between `feat:` and `fix:` and what it means for semantic versioning.

To set up the one click release, also requires tags to handle the versioned docs. There might be other-ways around this but this was the easiest for me. I really don't remember the 2-3 day fever dream of setting it up but I think the best thing is just to try and ask if anything doesn't work out. The important part to know is that everything is reversible **except** for publishing to PyPI. In that case, you basically have to create a new version. I think I ate up around 10-20 `Z`'s in `X.Y.Z` figuring this out.

**Comment by aaronkl** [comment]
We decided in a separate discussion to conform to convential-commit from now on. PR with commitzen as pre-commit  follows
