### ISSUE TITLE
Support FSDP and DataParallel (without find_unused_parameters=True)

### ISSUE THREAD

**Issue by rheasukthanker** [whittle-org/whittle#97]
**Is your feature request related to a problem? Please describe.**
Problem:
1. [**DDP strategy**](https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.strategies.DDPStrategy.html#lightning.pytorch.strategies.DDPStrategy) works for supernet training (eg: sandwich and random) only when **_find_unused_parameters_** is set to true and **static_graph** is set to False. This however leads to < 2x slow down check [this](https://github.com/Lightning-AI/pytorch-lightning/issues/17212#issuecomment-1493319675)
2. [**FSDP**](https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.strategies.FSDPStrategy.html) is crucial for larger models (eg: llama-7b doesn't fit on a single H100, hence we can't use DDP or DP). FSDP with the lightning trainer and whittle model leads to "All sharded parameters that received a gradient in the post-backward should use `_saved_grad_shard". Note this doesn't happen with the standard strategy. 

**Describe the solution you'd like**
Cleanest solution would be to add a wrapper class **FSDPGPT**, which instead of weight slicing applies weight masking. This way gradient shape for parameters across subnetwork stays the same

**Additional context**

- [x] Add minimal example to reproduce the error
- [ ] Add minimal example for DDP (with and without **_find_unused_parameters_** and **static_graph** set)

**Comment by rheasukthanker** [comment]
- This currently seems to work out of the box for single node. Yet to be tested across multiple nodes

**Comment by rheasukthanker** [comment]
@timurcarstensen and me discussed this and following are our takeaways:
1. Since sandwich scheme already samples the largest architecture (touching upon all model params for grad computation), the size of grads for DDP or FSDP synchronization are same and there is no shape mismatch
2. We tested FSDP (single and multi-node) and it runs fine
3. Shape mismatch might be an issue for random sampling strategy (where a different arch is sampled on every gpu and largest parameter might not be used for grad computation). However since sandwich scheme is usually better than random sampling we don't think we gain a lot from implementing masking specifically for random sampling.

**Comment by timurcarstensen** [comment]
@rheasukthanker add PR that throws an error when a user tries to use random sampling w/FSDP

**Comment by aaronkl** [comment]
@rheasukthanker can we close this?

**Comment by rheasukthanker** [comment]
We have an example to test fsdp here https://github.com/rheasukthanker/dist-debug/
